<a href="https://colab.research.google.com/github/vini1lol/Havardx/blob/master/week2Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import

In [0]:
import numpy as np
import random

#1


##Numpy.Zeros
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

In [0]:
# np.zeros?

In [226]:
np.zeros((3,3,))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##Exercise

In [0]:
def create_board():
  a = np.zeros((3,3),dtype=int)
  return a

In [8]:
board = create_board()
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# 2

In [0]:
def place(board, player, position):
  x,y = position
  if (x >= 0 and x<=3) and (y>=0 and y<=3):
    if board[x][y] == 0:
      board[x][y]=player
  return board


In [40]:
place(board,1,(0,0,))
board

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

#3

##Numpy.where
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.where.html

In [0]:
# np.where?

In [230]:
np.where(board==1)

(array([0, 2]), array([2, 1]))

##Exercise

In [0]:
def possibilities(board):
  b=[]
  a = np.where(board==0)
  for i in range(a[0].shape[0]):
    b.append((a[0][i],a[1][i]))
  return b

In [131]:
a = possibilities(board)
a

[(1, 2), (2, 0)]

#4

##Random.choice
https://pynative.com/python-random-choice/

In [0]:
# random.choice?

In [233]:
random.choice([1,2,3,5,7,8,4])

5

##Exercise

In [0]:
random.seed(1)
def random_place(board, player):
  a = random.choice(possibilities(board))
  place(board,player,a)



In [133]:
random_place(board,2)
board

array([[2, 2, 1],
       [2, 2, 2],
       [0, 1, 2]])

#5

In [234]:
random.seed(1)
board = create_board()
player = 1
for i in range(3):
  for player in [1,2]:
    random_place(board,player)
board

array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

#6

##Numpy.all
https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html

In [0]:
# np.all?

In [243]:
(board==0).all(0)

array([False, False, False])

In [236]:
(board==0).all()

False

In [237]:
np.all(board==0)

False

##Numpy.any
https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html

In [0]:
# np.any?

In [240]:
(board==0).any(0)

array([ True, False,  True])

In [241]:
(board==0).any()

True

##Exercise

In [0]:
def row_win(board, player):
  if (board==player).all(0).any():
    return True
  return False

In [136]:
row_win(board,1)

False

#7

In [0]:
def col_win(board, player):
  if (board==player).all(1).any():
    return True
  return False

In [138]:
b = create_board()
place(b,1,(0,0,))
place(b,1,(0,1))
place(b,1,(0,2))
col_win(b,1)

True

In [139]:
col_win(board,1)

False

#8

##numpy.diag 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html

In [0]:
# np.diag?

In [224]:
board

array([[2, 2, 1],
       [0, 2, 0],
       [0, 1, 2]])

In [223]:
np.diag(board)

array([2, 2, 2])

## Numpy.fliplr
https://docs.scipy.org/doc/numpy/reference/generated/numpy.fliplr.html

In [0]:
# np.fliplr?

In [222]:
np.fliplr(board)

array([[1, 2, 2],
       [0, 2, 0],
       [2, 1, 0]])

In [225]:
np.diag(np.fliplr(board))

array([1, 2, 0])

##Exercise

In [0]:
def diag_win(board, player):
  if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
    return True
  return False

In [0]:
board[1][1]=2

In [155]:
diag_win(board,2)

True

#9

In [0]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board,player) or col_win(board,player) or diag_win(board,player):
          winner = player
        pass
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

In [144]:
evaluate(board)

2

In [245]:
random.seed(7)
b,player= create_board(),1
for i in range(9):
  random_place(b,player)
  if player == 1:
    player=2
  else:
    player =1
print(b)
print(evaluate(b))

[[1 2 2]
 [2 1 1]
 [1 1 2]]
-1


#10

In [0]:
random.seed(1)
def play_game():
  board, winner = create_board(),0
  while winner==0:
    for player in [1,2]:
      random_place(board,player)
      winner = evaluate(board)
      if winner !=0:
        break
  return winner

In [220]:
play_game()

1

In [187]:
results=[]
random.seed(1)
for i in range(1000):
  results.append(play_game())
results
results = np.array(results)
(results==1).sum()

591

#11



In [0]:
random.seed(1)
def play_strategic_game():
  board, winner = create_board(),0
  player =2
  board[1,1]=1
  while winner==0:
    for player in [2,1]:
      random_place(board,player)
      winner = evaluate(board)
      if winner !=0:
        break
  return winner

In [216]:
random.seed(1)
results =[]
for i in range(1000):
  results.append(play_strategic_game())
results.count(1)

716